[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
axum = "0.8.3"
http-body-util = "0.1.3"

[dev-dependencies]
tower = { version = "0.5.2", features = ["util"] }
